### ISSUE TITLE
Email no tiene link para activar cuenta

### ISSUE THREAD

**Issue by Phosphorus-M** [Desarrollo-Util/learnthis-beta#1]
Llega el email pero el boton no redirecciona para activar la cuenta:
![image](https://user-images.githubusercontent.com/19656993/143486568-d4909f37-89f2-4c42-9dc7-ca3222e11d9b.png)

**Comment by Josyto** [comment]
Había un error en una variable de entorno la cual se usa para generar ese enlace.
Al arreglarlo, debería generar bien este y los demás enlaces de los correos.

También se actualizaron  el resto de enlaces de las políticas y footer
