### ISSUE TITLE
Alinear visualmente los iconos de las flechas [Soy un capullo, lo sé jajaja]

### ISSUE THREAD

**Issue by husseincak** [Desarrollo-Util/learnthis-beta#10]
Aunque los iconos están correctamente alineados, la carga visual del icono está realmente un pixel a la derecha y izquierda espectivamente, por lo que se siente que no están correctamente alineados.

Mal:
![image](https://user-images.githubusercontent.com/6590146/143492537-ed359bda-cf26-4516-9115-3469fd0740fb.png)

Bien:
![image](https://user-images.githubusercontent.com/6590146/143492551-cb6349c6-2957-4028-b068-488ddb189aa2.png)

Podéis matarme xD

**Comment by Josyto** [comment]
Se han modificado los iconos de las flechas, el problema es que estos iconos están medio pixel desfasados.
Que conste que estos iconos son de Heroicons y vienen así de la web, por si alguien los está utilizando, que los centre bien previamente (Illustrator o similares), ocurre con todas las flechas, unas tienen el pixel en horizontal y otras en vertical.
