### ISSUE TITLE
El icono de cerrar sesión me recuerda al de cambiar modo oscuro / modo light

### ISSUE THREAD

**Issue by husseincak** [Desarrollo-Util/learnthis-beta#11]
Este icono me confunde:
![image](https://user-images.githubusercontent.com/6590146/143492954-f925ea6b-ac67-4143-ba02-62626459a502.png)

Por ejemplo en clickup:
![image](https://user-images.githubusercontent.com/6590146/143492831-207b51b6-0ebd-47ee-88e5-ec50f197bf4a.png)

O notion: 
![image](https://user-images.githubusercontent.com/6590146/143493001-dc9b9f0e-1d70-4b39-8124-f2c9a84ae05d.png)

**Comment by Josyto** [comment]
Se ha cambiado el icono por uno más intuitivo

![image](https://user-images.githubusercontent.com/18529351/143583313-6accd962-3edf-4c31-aeb5-337f5e61a93f.png)
