### ISSUE TITLE
Pantallazo del checkout cuando haces click en un pack que ya has comprado

### ISSUE THREAD

**Issue by davidhfabian** [Desarrollo-Util/learnthis-beta#12]
Tambien estaria bien marcar de alguna manera que ya fue comprado

https://user-images.githubusercontent.com/49488765/143493646-a452b41b-69ba-4174-a676-0d1a9f4bca32.mov

**Comment by Josyto** [comment]
- En cliente se ha introducido un pequeño loader mientras se comprueba si tienes el curso, aunque este loader no debería aparecer ya que no deberías poder acceder a esta página por un botón de comprar si dispones de un curso tal y como comenta la issue #4 . 

- En servidor te redirige a tus cursos si accedes a la URL de compra de un curso ya adquirido
