### ISSUE TITLE
Registro social

### ISSUE THREAD

**Issue by Josyto** [Desarrollo-Util/learnthis-beta#16]
Se producen errores con ciertas cuentas sociales, en principio sólo con Github. Creemos que el error se debe a que hay algún campo que recogemos y que consideramos obligatorio pero que no lo es, por lo que a las personas que no tienen ese campo e intentan registrarse con esa cuenta les devuelve un error.

Estamos investigándolo para intentar acotar el error, nos vendría genial saber de alguna persona que tenga este problema para poder realizar pruebas en los directos.

**Comment by Josyto** [comment]
Se refactorizará esta parte para adecuarla a los datos de facturación y solucionar el tema de las facturas

**Comment by luciferfran** [comment]
Buenas! A mí no me deja registrarme con Google, llego a la página de oauth de google acepto mi usuario y a la vuelta en learnthis
"Error en el servidor, inténtelo más tarde"
Y esto arroja el log de javascript
signup-6ef2a3831e22e1a6.js:1 NOC-0001: Error en el servidor, inténtelo de nuevo más tarde

**Comment by Josyto** [comment]
@luciferfran
Buenas Fran, en primer lugar gracias por el reporte.
Seguimos teniendo ciertos problemas con el registro social cuando falta cierta información en el perfil de la red social. Tenemos pendiente solucionar esto.
Cuando lo suba avisaré por esta misma issue para que vuelvas a probar con la misma cuenta.

**Comment by Josyto** [comment]
Con la última subida debería haberse solucionado, si se repite se reabrirá la issue
