### ISSUE TITLE
Registro social

### ISSUE THREAD

**Issue by adrianmartindev** [Desarrollo-Util/learnthis-beta#18]
Cuando haces un registro social, te dice que ya puedes acceder con esa cuenta pero no te mantiene logeado, quizás sería buena idea que una vez registrado te mantuviese logeado. 

Lo he probado con Google, no se si con otros pasará igual.

**Comment by Josyto** [comment]
Con la última subida debería haberse solucionado, si se repite se reabrirá la issue
