### ISSUE TITLE
Popup presente en configuración cookies (móvil)

### ISSUE THREAD

**Issue by cecicifu** [Desarrollo-Util/learnthis-beta#19]
Al darle clic al botón de configuración de cookies, el popup sigue estando presente y por lo cual no permite ver todas las opciones de configuración ni botones de acciones.
![IMG_20211230_104947](https://user-images.githubusercontent.com/15237067/147740996-be3a8868-38d5-4c48-88db-c56b8500943b.jpg)

Imagen realizada desde un Xiaomi Redmi Note 8 Pro

**Comment by Josyto** [comment]
Muchas gracias por el reporte @cecicifu, en cuanto podamos lo revisamos pero huele a z-index o contexto de apilamiento de lejos jaja

**Comment by Josyto** [comment]
La configuración de cookies ya aparece por encima del popup
