### ISSUE TITLE
Registro temporalmente marca la contraseña como erronea

### ISSUE THREAD

**Issue by Phosphorus-M** [Desarrollo-Util/learnthis-beta#2]
La contraseña se marca como erronea un segundo antes de enviarse el registro, funciona pero es algo visual.

**Comment by Josyto** [comment]
Este fallo se producía al vaciar el input de contraseña según se envía el formulario.
Se ha actualizado para que sólo se vacíe en caso de error lo cual debería evitar este comportamiento.
