### ISSUE TITLE
Link logo Footer

### ISSUE THREAD

**Issue by KevinFrutos** [Desarrollo-Util/learnthis-beta#21]
El logo del Footer no tiene link, normalmente toda las webs que suelo ver, cuando ponen el logo de la "empresa" en el footer, suelen ponerle un link a la misma pagina.

**Comment by Josyto** [comment]
Tras darle una pensada hemos decidido no poner el enlace ya que el footer sólo se encuentra en la propia Home o en la página de Beta que desaparecerá en la salida a producción. 

Quizás si en un futuro está en más páginas y tiene sentido a nivel de UX lo introduzcamos.

No obstante muchas gracias por la sugerencia @KevinFrutos
