### ISSUE TITLE
Botón "Recuperar contraseña"

### ISSUE THREAD

**Issue by KevinFrutos** [Desarrollo-Util/learnthis-beta#23]
URL: https://learnthisdev.com/recover-pass

El texto del botón "Recuperar contraseña" se ve como aprisionado, como que le falta padding o agrandar el width del botón para que se vea la frase completa en una línea.

**Comment by Josyto** [comment]
Se han fixeado los tamaños de los botones, ahora ningún botón debería tener problemas de aprisionamiento con el texto.
