### ISSUE TITLE
Abrir link en una nueva pestaña "política de privacidad"

### ISSUE THREAD

**Issue by KevinFrutos** [Desarrollo-Util/learnthis-beta#24]
URL: https://learnthisdev.com/signup

Sería interesante que el link a la "política de privacidad" tuviese un target="_blank" ya que en mi opinión, no interesa que el usuario pierda los datos ya introducidos.

**Comment by Josyto** [comment]
Se han cambiado todos los enlaces a políticas para que se abran en una nueva pestaña.
