### ISSUE TITLE
UX/UI Registro Formato de contraseña incorrecta si es muy corta

### ISSUE THREAD

**Issue by Intuizion** [Desarrollo-Util/learnthis-beta#25]
Cuando en el registro de un nuevo usuario se utiliza una contraseña muy corta (he probado 5 letras) entonces pone en rojo " Formato de contraseña incorrecto" debajo del campo para contraseña. 

Creo de que debería indicarse la política de contraseñas cambiando el texto en rojo por ""La contraseña tiene que el formato X"

Es UX/UI pero es obligatorio si no queréis perder registros con eso.
![Captura de pantalla 2022-02-03 a las 16 25 08](https://user-images.githubusercontent.com/74659475/152374105-da0d0c06-4fdf-4865-a228-bc046c73026c.png)

**Comment by luisalbertmschz** [comment]
Esto es una muy buena oportunidad de mejora al momento de mostrar ese mensaje cuando ingresamos un password que no cumple con el formato correcto que se espera...no estaría mal si desplegasemos las condiciones que se están cumpliendo al momento de digitar el password a establecer para la cuenta y cuales no.

Por ejemplo:
![PasswordVal](https://user-images.githubusercontent.com/43512313/152393523-79552a32-07c3-4f9d-90ee-b72e70ef679f.png)
![PasswordVal2](https://user-images.githubusercontent.com/43512313/152393526-272ee698-8c2f-4701-b434-d2538e306642.png)

**Comment by Josyto** [comment]
Se ha añadido algo similar a lo sugerido para que los usuarios lo tengan más claro.
Muchas gracias por el reporte y las sugerencias.

![image](https://user-images.githubusercontent.com/18529351/152548997-a9338c1a-d18e-450e-848b-4e3032bdbaa7.png)
