### ISSUE TITLE
Error al pagar con Paypal

### ISSUE THREAD

**Issue by Intuizion** [Desarrollo-Util/learnthis-beta#26]
Al comprar un curso y dar al botón de pagar con Paypal me da un error (mirar captura de pantalla). Sale dos popups de error interno en servidor

Nota: No sé si afecta pero antes del dar al botón de pagar de Paypal, he cambiado varias veces el país de residencia para ver como cambiaba el IVA. ¿Afecta? Vete a saber que pone el código...
![Captura de pantalla 2022-02-03 a las 16 51 16](https://user-images.githubusercontent.com/74659475/152378625-bd4f12a5-fb85-47ee-bbf9-210436a75ab5.png)

**Comment by Josyto** [comment]
El país puede afectar, hay paises que la propia plataforma no permite.
Por cierto ¿usaste las cuentas que dejamos en las instrucciones no?

No obstante lo revisaré para que el error sea correcto e indique porqué falla

**Comment by Intuizion** [comment]
Mas detalles: Cuando le dí al botón de pagar estaba seleccionado país España. No me llegó a pedir los datos de usuario de Paypal. El error fué antes de enlazar con Paypal y es un error vuestro y no de Paypal. Antes de seleccionar España tenía seleccionado otros países para ver como manejabais el IVA y si se puede hacer como en Netflix y suscribirme desde Turquía para pagar menos ;-)  

Creo que el problema es de alguna variable vuestra del formulario y de cómo hacéis la llamada a la API de Paypal. 

![Captura de pantalla 2022-02-03 a las 16 51 48](https://user-images.githubusercontent.com/74659475/152415568-7a971c69-4971-41d2-9b24-3b83043e47cc.png)
a

**Comment by Josyto** [comment]
Gracias por el detalle, revisando el error en Sentry nos indica bien que es algo nuestro.
Hicimos un pequeño cambio para coger un valor de la propia libreria de PayPal y está dando problemas.

A ver si hoy puedo solucionarlo y quitar este problema.

**Comment by Josyto** [comment]
Se ha localizado el error y se ha fixeado.
Queda pendiente revisar ciertos errores cuando es Paypal o Stripe los que no te permiten pagar por situarte en ciertos países.
