### ISSUE TITLE
En pago por paypal la venta popup de pago por paypal desaparece.

### ISSUE THREAD

**Issue by Intuizion** [Desarrollo-Util/learnthis-beta#27]
Estaba pagando por Paypal. Me sale la pagina popup para meter usuario y password de Paypal. Como voy a copiar los datos de vuestra web, que está en otra pestaña, pues cambio de pestaña de chrome. Al volver a la pestaña de Learnthis me sale la captura. 
Si le doy a continuar me vuelve a abrir la web popup de paypal. Creo que si en vez de cambiar de pestaña de chrome es ir a otra aplicación como un gestor de passwords pasa lo mismo. A mi en otras web que tienen paypal no me pasa. deberíais cambiarlo para evitar fricción en el pago. 
![Captura de pantalla 2022-02-10 a las 22 21 28](https://user-images.githubusercontent.com/74659475/153499249-d25bd696-1d8c-4f6b-9f43-6698d45b42d2.png)

**Comment by Josyto** [comment]
Entiendo que te refieres a que en vez de un popup aparezca la propia web de paypal de forma que en una única pestaña hagas el pago y luego te devuelva a la web.
Ahora mismo el boton de continuar te muestra el popup que queda oculto si cambias de navegador o pestaña, para precisamente que peudas copiar tus datos de un gestor o consultarlos y luego volver a la parte de pago.

**Comment by Intuizion** [comment]
Si. Todas las integraciones que veo de Paypal te llevan a la web de Paypal (captura adjunta). Podéis implementar la integración que queráis, faltaba más :-) Pero supongo que implementar la web de paypal y al finalizar volver a learnthis tiene las ventajas (para mí):
- La web de Paypal da más sensación de seguridad al meter tus credenciales en la URL de Paypal y pillar tu cuenta de paypal de las cookies. El popup de Paypal puede dar a alguna gente sensación de phising. 
- La popup que al dejar de estar activa desaparece y para que vuelva a salir le tienes que dar a continuar, me resultó raro y con fricción.

Está claro que no es un error vuestro, sino un tema de UX por la implementación de Paypal. A lo mejor podéis dejarlo así y mirar si os genera abandono del proceso de compra en ese punto. A mi me faltan datos de uso para decir cual es el mejor método. Es pura impresión mía. 
![Captura de pantalla 2022-02-11 a las 11 59 31](https://user-images.githubusercontent.com/74659475/153580593-c4a7570c-d740-4398-91d8-c5d0086c547c.png)
)

**Comment by Josyto** [comment]
He revisado la documentación y las diferentes implementaciones y en principio no vamos a cambiarlo.

La opción de la redirección es de una implementación que ellos consideran legacy, por lo que para hacerlo habría que realizar la implementación de forma manual, y la documentación pues como que no ayuda. 
No obstante lo apuntaré como futura mejora y comprobaremos las tasas de abandono como comentas.

PayPal siempre lo mejor xD

**Comment by Josyto** [comment]
No obstante como comentario final aunque desaparezca si vuelves a pulsar en la web reaparece en primer plano, al menos ni tan mal xD
