### ISSUE TITLE
[VISUAL BUG] Boton Indice de curso desaparece

### ISSUE THREAD

**Issue by Javiertis** [Desarrollo-Util/learnthis-beta#3]
Cuando llega a 1024px hasta los 774px desaparece tanto el indice del curso y el boton.
Desaparece:
![imagen](https://user-images.githubusercontent.com/34624890/143487086-f2776fc0-b426-437d-a965-2d845e5c26e0.png)
Aparece el menu:
![imagen](https://user-images.githubusercontent.com/34624890/143487109-697a140a-fd21-4e9c-b375-c3eae5ac33ed.png)
Aparece el boton de menu:
![imagen](https://user-images.githubusercontent.com/34624890/143487146-b9368f97-0d4b-4b70-a20d-a37bb834a0ea.png)

**Comment by Josyto** [comment]
Se han revisado y ajustado los estilos en todas las resoluciones para que o bien aparezca el menú fijo a la derecha o el botón de apertura del menú.
