### ISSUE TITLE
No detecta curso comprado

### ISSUE THREAD

**Issue by DorianDesings** [Desarrollo-Util/learnthis-beta#4]
Aunque haya comprado los cursos en la home sigue poniendo comprar

![image](https://user-images.githubusercontent.com/35946850/143487761-9e6a460a-61e6-40fe-810b-06a327aa4cac.png)

**Comment by Josyto** [comment]
Se ha implementado la funcionalidad para que no te permita comprar los cursos que ya tienes. En el caso de un pack te indicará que ya tienes ciertos cursos como aviso o si tienes todos tampoco te dejará comprar el pack
