### ISSUE TITLE
Algo no es valido en el registro

### ISSUE THREAD

**Issue by Phosphorus-M** [Desarrollo-Util/learnthis-beta#5]
Propongo explicar mejor que es lo que falla, si bien marca el error en la contraseña no se sabe exactamente cual es el problema

https://user-images.githubusercontent.com/19656993/143487800-6107816f-1612-4d25-881e-56124f8855e7.mp4

**Comment by Josyto** [comment]
Se ha introducido la validación de contraseña que faltaba en cliente para que el error sea mas coherente y usable
![image](https://user-images.githubusercontent.com/18529351/143844010-b8b269e5-eb39-43a0-94d9-6c90ddd6034d.png)
