### ISSUE TITLE
En my-account no me sale ningún pedido realizado o compra

### ISSUE THREAD

**Issue by husseincak** [Desarrollo-Util/learnthis-beta#6]
He comprado el curso "Asincronismo en JS" con stripe y el mail hussein@isabellatech.es.
Si entro en este link me sale que no he realizado ningún pedido
https://learnthisdev.com/my-account.

Adjunto capturas:
![image](https://user-images.githubusercontent.com/6590146/143488753-a763d40a-cff3-4531-a0df-30f2d44f8b8f.png)

![image](https://user-images.githubusercontent.com/6590146/143488783-cafe23f4-3ba5-4f0f-8fe3-85dd7ecadebf.png)

![image](https://user-images.githubusercontent.com/6590146/143488775-592bf6c2-e39c-4394-8f6d-00fb5ff015a4.png)

**Comment by husseincak** [comment]
Pasado un tiempo, ya aparece el pedido. Pero he comprado otro y no sale el segundo, por lo que supongo que tarda bastante en cargar los pedidos una vez los compras:
![image](https://user-images.githubusercontent.com/6590146/143492445-20c1af03-8ed7-47c0-bfb1-5d9b29afe59b.png)

![image](https://user-images.githubusercontent.com/6590146/143492420-abf350fe-bb0a-4bde-ba95-2e77e50e1c35.png)

**Comment by pablocdev** [comment]
Posiblemente tenga relación con la caché de CloudFlare.

Probablemente eliminaremos CloudFlare de los frontales, ya que Vercel tiene su propia implementación anti DDoS. 

Queda a la espera de poder probar esto.

**Comment by Josyto** [comment]
Actualmente se ha eliminado el proxy de Cloudfare tal y cómo aconseja Vercel. Para probarlo habrá que borrar los pedidos y volverlos a realizar por lo que se podría probar con una cuenta nueva para ver si el error sigue persistiendo.

PD: @husseincak Gracias por el enlace, lo dejo por aquí por si alguien quiere echarle un vistazo 
https://vercel.com/support/articles/using-cloudflare-with-vercel

**Comment by husseincak** [comment]
Buenas! He comprobado, y sigue pasando, pero ahora tarda un par de minutos, pero no es como antes, que tardaba una media hora. Por lo que supongo que ahora si que no habría problemas

**Comment by AngelGris76** [comment]
Hoy me pasó los mismo desde FireFox 94 en Linux-Mint. Sin embargo la pantalla de chrome 96 si mostraba el curso
![cuenta-registrada-con-github](https://user-images.githubusercontent.com/76565892/143691572-761f10ec-7803-4a37-a6b1-a0def731d9d0.png)
o

**Comment by Josyto** [comment]
Gracias por el feedback @AngelGris76 y @husseincak, creo que el problema es de caché aunque tengo pendiente investigarlo ya que aún no he logrado replicar el fallo. No debería tardar tanto ya que en el correo se envía la factura y en ese momento la información del pedido ya está en BBDD (de hecho bastante antes) por lo que el problema es que no lo carga en el front.
A ver si mañana logro ver porqué sucede esto.

**Comment by Josyto** [comment]
Ya está solucionado, había varios problemas de caché tanto por parte de Cloudfare como en cliente. Si se vuelve a repetir no dudéis en reabrir al issue
