### ISSUE TITLE
Link the logo no Funciona en la compra de tarjetas

### ISSUE THREAD

**Issue by RogeMateos** [Desarrollo-Util/learnthis-beta#7]
![Screenshot 2021-11-25 at 18 43 47](https://user-images.githubusercontent.com/2786311/143489786-1e0fc4e4-f038-4dbd-9971-88c57e6b4415.png)

**Comment by Josyto** [comment]
La idea es que desde esta página se pueda volver hacia atrás pulsando el botón de la web para mejorar la conversión de ventas.
Es tema de marketing y es intencionado en este caso.
