### ISSUE TITLE
Placeholder incorrectos en el cambio de datos

### ISSUE THREAD

**Issue by Javiertis** [Desarrollo-Util/learnthis-beta#8]
He intentado cambiar los datos y me aparece pass en el nombre y nuevo email en el apellido.
![imagen](https://user-images.githubusercontent.com/34624890/143490345-afd2bcf3-bab1-4a51-91e7-ee20b7e62fa5.png)

**Comment by Josyto** [comment]
Se han corregido los placeholder en el modal que nos indicabas, muchas gracias por el feedback
![image](https://user-images.githubusercontent.com/18529351/143583808-229469cf-39f4-45e1-80d6-8995fe490ac9.png)
