### ISSUE TITLE
Avatar parpadea cuando cambias curso

### ISSUE THREAD

**Issue by husseincak** [Desarrollo-Util/learnthis-beta#9]
Os dejo video:

https://go.isabellatech.co/THZ3CK

En algún momento, en safari se pone a parpadear solo tambien. Está en el video. Si necesitáis que inspeccione algo, avisarme sin problemas!

**Comment by Josyto** [comment]
Se ha memoizado el componente para que no se monte al cambiar de ruta.
El problema se podía simular si deshabilitabas la cache en chrome y ya no sucede.
En safari no debería dar problemas tampoco, sino se reabre la issue.
